In [1]:
import numpy as np

# carregando os dados com numpy
entradas = np.genfromtxt('iris.data', delimiter=',', usecols=(0,1,2,3))
saidas = np.genfromtxt('iris.data', delimiter=',', usecols=(4))
print(len(entradas))
print(len(saidas))

150
150


In [2]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

# mostrando as 5 primeiras amostras que são Iris-setosa
print(entradas[:5])
print(saidas[:5])

print('---------------------')

# mostrando as 5 últimas amostras que são de Iris-virginica
print(entradas[-5:])
print(saidas[-5:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0. 0. 0. 0. 0.]
---------------------
[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[2. 2. 2. 2. 2.]


In [3]:
# vou utilizar 105 amostras para treino sendo 35 de cada classe
entradas_treino = np.concatenate((entradas[:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35], saidas[50:85], saidas[100:135]))
print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [4]:
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))
print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [5]:
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [6]:
treinamento = SupervisedDataSet(4, 1)
for i in range(len(entradas_treino)):
    treinamento.addSample(entradas_treino[i], saidas_treino[i])
print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [7]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.3)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.012 ]')
('correct:', '[0     ]')
error:  0.00006914
('out:    ', '[0.006 ]')
('correct:', '[0     ]')
error:  0.00001682
('out:    ', '[0.018 ]')
('correct:', '[0     ]')
error:  0.00015423
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00028195
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008374
('out:    ', '[0.011 ]')
('correct:', '[0     ]')
error:  0.00005977
('out:    ', '[0.061 ]')
('correct:', '[0     ]')
error:  0.00185809
('out:    ', '[0.018 ]')
('correct:', '[0     ]')
error:  0.00016594
('out:    ', '[0.032 ]')
('correct:', '[0     ]')
error:  0.00049799
('out:    ', '[0.02  ]')
('correct:', '[0     ]')
error:  0.00020304
('out:    ', '[0.028 ]')
('correct:', '[0     ]')
error:  0.00038624
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00002873
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00018146
('out:    ', '[0.007 ]')
('correct:', '[0     ]')
error:  0.00002209
('out:    ', '[0

0.010730564359135268

In [8]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# treinando a rede
for epoca in range(2000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.002]')
('correct:', '[0     ]')
error:  0.00000170
('out:    ', '[-0.012]')
('correct:', '[0     ]')
error:  0.00007384
('out:    ', '[0.007 ]')
('correct:', '[0     ]')
error:  0.00002396
('out:    ', '[0.016 ]')
('correct:', '[0     ]')
error:  0.00012458
('out:    ', '[-0.002]')
('correct:', '[0     ]')
error:  0.00000149
('out:    ', '[-0.005]')
('correct:', '[0     ]')
error:  0.00001276
('out:    ', '[0.058 ]')
('correct:', '[0     ]')
error:  0.00166128
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00003453
('out:    ', '[0.015 ]')
('correct:', '[0     ]')
error:  0.00011473
('out:    ', '[0.003 ]')
('correct:', '[0     ]')
error:  0.00000451
('out:    ', '[0.017 ]')
('correct:', '[0     ]')
error:  0.00014833
('out:    ', '[-0.01 ]')
('correct:', '[0     ]')
error:  0.00004853
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00003511
('out:    ', '[-0.011]')
('correct:', '[0     ]')
error:  0.00006322
('out:    ', '[-

0.019761028950724718

In [9]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.7)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.029]')
('correct:', '[0     ]')
error:  0.00041629
('out:    ', '[-0.044]')
('correct:', '[0     ]')
error:  0.00097455
('out:    ', '[-0    ]')
('correct:', '[0     ]')
error:  0.00000001
('out:    ', '[-0.003]')
('correct:', '[0     ]')
error:  0.00000414
('out:    ', '[-0.023]')
('correct:', '[0     ]')
error:  0.00026098
('out:    ', '[-0.04 ]')
('correct:', '[0     ]')
error:  0.00081586
('out:    ', '[0.139 ]')
('correct:', '[0     ]')
error:  0.00960502
('out:    ', '[-0.025]')
('correct:', '[0     ]')
error:  0.00030746
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009758
('out:    ', '[-0.012]')
('correct:', '[0     ]')
error:  0.00006722
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00027632
('out:    ', '[-0.05 ]')
('correct:', '[0     ]')
error:  0.00122975
('out:    ', '[-0.015]')
('correct:', '[0     ]')
error:  0.00010527
('out:    ', '[-0.047]')
('correct:', '[0     ]')
error:  0.00112730
('out:    ', '[-

0.008519328125516918