In [8]:
import numpy as np

In [9]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.delete(a, 1, 0)

array([[1, 2],
       [5, 6]])

In [11]:
np.delete(a,0,1)

array([[2],
       [4],
       [6]])

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.delete(a,np.s_[::2],0)

array([[ 4,  5,  6],
       [10, 11, 12]])